### ISSUE TITLE
Using EventLinker.on with instance methods

### ISSUE THREAD

**Issue by eehusky** [mdapena/pyventus#26] opened 2024-10-26 17:50 UTC
This could be a bug report or an enhancement/new feature request/or a user error.

I was trying to setup some instance methods as event handlers but it doesnt look like the EventLnker.on decorator supports this particular use case.  

I figured out a way to make it do what i was after (see ClassB below) but im kind of curious if this is intentional and there is a compelling reason why you shouldn't use instance methods as handlers?

I tried to setup a wrapper for the EventLinker.on decorator that would pass through self but my decorator skills arent up to the task. 

```
@dataclass
class MyEvent:
    a: str
    b: str

class ClassA:
    @EventLinker.on(MyEvent)
    def on_event(self,event):
        """
        This doesnt work because the decorator swallows self
        so you get a missing parameter error.
        """


class ClassB:
    def __init__(self):
        """
        this works
        setup the event handlers using a closure 
        """
        @EventLinker.on(MyEvent)
        def _on_event(event):
            self.on_event(event)

    def on_event(self,event):
        """
        """
```

**Comment by mdapena** [comment] 2024-10-27 04:43
Thanks for reporting! The issue you're experiencing with the `EventLinker` and the `ClassA` example is actually related to how Python handles object-oriented programming, rather than being a problem with `pyventus` itself. So, let’s dive into this a bit to clarify what’s going on and hopefully make things clearer.

When you use the `EventLinker.on()` decorator like that, you’re actually subscribing to the class function `ClassA.on_event` instead of the instance method `self.on_event`, as you might have expected. This happens because of how Python manages objects and their classes, which can sometimes be a bit complex.

Since the callback you’re subscribing to is the class function, it requires two parameters: `self` and `event`. However, Python doesn’t automatically pass the `self` argument because we’re not working with the instance method in this case. As a result, when `MyEvent` is emitted, only the `MyEvent` object is passed as the first argument, leaving the second one missing. You can see this clearly in the error message you might be getting:

````console
TypeError("ClassA.on_event() missing 1 required positional argument: 'event'")
````

This error specifically points to the `ClassA.on_event()` function, confirming that it’s not an instance method that’s being called.

Now, if we look at `ClassB`, it works perfectly fine because in that case, you’re subscribing to a local function and using an instance of that class to call the method, which allows Python to automatically pass the `self` reference along with the `MyEvent` object. It’s important to note that this behavior is specific to thread-based emitters, such as `AsyncIOEventEmitter` or `ExecutorEventEmitter`, where functions can access the same memory context.

Finally, to properly subscribe to instance methods with the `EventLinker`, you can refer to the following example, which ensures that everything functions as intended:

````python
from dataclasses import dataclass
from pyventus.events import EventLinker, AsyncIOEventEmitter


@dataclass
class MyEvent:
    a: str
    b: str


class ClassC:
    def __init__(self):
        # Subscribe self.on_event (the actual instance method) to MyEvent during initialization 
        EventLinker.subscribe(MyEvent, event_callback=self.on_event)

    def on_event(self, event):
        print(f"self: {self}", f"event: {event}")

# Create an instance and register its method with the linker
c = ClassC()

# Create an event emitter and emit a MyEvent instance
event_emitter = AsyncIOEventEmitter()
event_emitter.emit(MyEvent(a="a", b="b"))
````

I will be closing this issue as it is not a bug. If you have any further questions or if you believe there is still an issue, please feel free to reopen it.

**Comment by mdapena** [comment] 2024-10-27 04:45
Other than that, thanks for pointing this out; it’s a really interesting use case example. I’ll make sure it gets included in the next update of the documentation, as it could be helpful for others as well. If you’re curious about what’s coming next for Pyventus, be sure to check out [Pyventus v0.7.0 (unreleased)](https://mdapena.github.io/pyventus/dev/release-notes/#0.7.0), which features exciting updates like reactive programming, major optimizations, and much more.

**Closed by mdapena** 2024-10-27 04:45 UTC
Labels: bug
